import datetime

dept_data = [
    {
        "id": 1,
        "description": "",
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "DVAdmin团队",
        "sort": 1,
        "owner": "",
        "phone": "",
        "email": "",
        "status": 1,
        "creator_id": 1,
        "parent_id": None,
    },
    {
        "id": 2,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 2,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "技术部",
        "sort": 1,
        "owner": None,
        "phone": None,
        "email": None,
        "status": 1,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 3,
        "description": "",
        "modifier": "1",
        "dept_belong_id": 3,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "运营部",
        "sort": 2,
        "owner": "",
        "phone": "",
        "email": "",
        "status": 1,
        "creator_id": 1,
        "parent_id": 1,
    },
]

button_data = [
    {
        "id": 1,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "creator_id": 1,
    },
    {
        "id": 2,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "creator_id": 1,
    },
    {
        "id": 3,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "creator_id": 1,
    },
    {
        "id": 4,
        "description": "",
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "creator_id": 1,
    },
    {
        "id": 5,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "creator_id": 1,
    },
    {
        "id": 6,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "保存",
        "value": "Save",
        "creator_id": 1,
    },
    {
        "id": 7,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "导入",
        "value": "Import",
        "creator_id": 1,
    },
    {
        "id": 8,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "导出",
        "value": "Export",
        "creator_id": 1,
    },
    {
        "id": 9,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "重设密码",
        "value": "ResetPassword",
        "creator_id": 1,
    },
    {
        "id": 10,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "重置密码",
        "value": "DefaultPassword",
        "creator_id": 1,
    },
]

menu_data = [
    {
        "id": 2,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": 1,
            "update_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "create_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "icon": "cog",
            "name": "系统管理",
            "sort": 1,
            "is_link": 0,
            "web_path": "",
            "component": "",
            "component_name": "",
            "status": 1,
            "cache": 0,
            "visible": 1,
            "creator_id": 1,
            "is_catalog": 1,
        },
        "children": [
            {
                "id": 1,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "navicon",
                    "name": "菜单管理",
                    "sort": 1,
                    "is_link": 0,
                    "web_path": "/menu",
                    "component": "system/menu",
                    "component_name": "menu",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 3,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "users",
                    "name": "用户管理",
                    "sort": 6,
                    "is_link": 0,
                    "web_path": "/user",
                    "component": "system/user/index",
                    "component_name": "user",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 4,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "address-book",
                    "name": "角色管理",
                    "sort": 4,
                    "is_link": 0,
                    "web_path": "/role",
                    "component": "system/role/index",
                    "component_name": "role",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 5,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": 1,
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "bank",
                    "name": "部门管理",
                    "sort": 3,
                    "is_link": 0,
                    "web_path": "/dept",
                    "component": "system/dept/index",
                    "component_name": "dept",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 7,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "dot-circle-o",
                    "name": "菜单按钮",
                    "sort": 2,
                    "is_link": 0,
                    "web_path": "/menuButton",
                    "component": "system/menuButton/index",
                    "component_name": "menuButton",
                    "status": 1,
                    "cache": 0,
                    "visible": 0,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 8,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "bullseye",
                    "name": "按钮管理",
                    "sort": 2,
                    "is_link": 0,
                    "web_path": "/button",
                    "component": "system/button/index",
                    "component_name": "button",
                    "status": 1,
                    "cache": 0,
                    "visible": 0,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 9,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "compass",
                    "name": "接口白名单",
                    "sort": 7,
                    "is_link": 0,
                    "web_path": "/apiWhiteList",
                    "component": "system/whiteList/index",
                    "component_name": "whiteList",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
        ],
    },
    {
        "id": 15,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": 1,
            "update_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "create_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "icon": "book",
            "name": "日志管理",
            "sort": 3,
            "is_link": 0,
            "web_path": "",
            "component": "",
            "component_name": "",
            "status": 1,
            "cache": 0,
            "visible": 1,
            "creator_id": 1,
            "is_catalog": 1,
        },
        "children": [
            {
                "id": 16,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "file-code-o",
                    "name": "操作日志",
                    "sort": 2,
                    "is_link": 0,
                    "web_path": "/operationLog",
                    "component": "system/log/operationLog/index",
                    "component_name": "operationLog",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 19,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": 1,
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "bug",
                    "name": "前端错误日志",
                    "sort": 4,
                    "is_link": 0,
                    "web_path": "/frontendLog",
                    "component": "system/log/frontendLog/index",
                    "component_name": "frontendLog",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 20,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": 1,
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "file-text",
                    "name": "登录日志",
                    "sort": 1,
                    "is_link": 0,
                    "web_path": "/loginLog",
                    "component": "system/log/loginLog/index",
                    "component_name": "loginLog",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
        ],
    },
    {
        "id": 17,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": 1,
            "update_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "create_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "icon": "cogs",
            "name": "常规配置",
            "sort": 2,
            "is_link": 0,
            "web_path": "",
            "component": "",
            "component_name": "",
            "status": 1,
            "cache": 0,
            "visible": 1,
            "creator_id": 1,
            "is_catalog": 1,
        },
        "children": [
            {
                "id": 10,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "book",
                    "name": "字典管理",
                    "sort": 1,
                    "is_link": 0,
                    "web_path": "/dictionary",
                    "component": "system/dictionary/index",
                    "component_name": "dictionary",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 11,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "map",
                    "name": "地区管理",
                    "sort": 2,
                    "is_link": 0,
                    "web_path": "/areas",
                    "component": "system/areas/index",
                    "component_name": "areas",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 13,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "file-text-o",
                    "name": "附件管理",
                    "sort": 3,
                    "is_link": 0,
                    "web_path": "/file",
                    "component": "system/fileList/index",
                    "component_name": "file",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                    "is_catalog": 0,
                },
            },
            {
                "id": 26,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 10, 55, 42, 720749
                    ),
                    "icon": "desktop",
                    "name": "系统配置",
                    "sort": 0,
                    "is_link": 0,
                    "is_catalog": 0,
                    "web_path": "/config",
                    "component": "system/config/index",
                    "component_name": "config",
                    "status": 1,
                    "cache": 0,
                    "visible": 1,
                    "creator_id": 1,
                },
            },
        ],
    },
    {
        "id": 18,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": 1,
            "update_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "create_datetime": datetime.datetime(2022, 5, 18, 10, 55, 42, 720749),
            "icon": "external-link",
            "name": "DVAdmin官网",
            "sort": 4,
            "is_link": 1,
            "web_path": "https://django-vue-admin.com",
            "component": "",
            "component_name": "",
            "status": 1,
            "cache": 0,
            "visible": 1,
            "creator_id": 1,
            "is_catalog": 0,
        },
    },
]

menu_button_data = [
    {
        "id": 1,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/menu/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 1,
    },
    {
        "id": 2,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/menu/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 1,
    },
    {
        "id": 3,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/menu/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 1,
    },
    {
        "id": 4,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/menu/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 1,
    },
    {
        "id": 5,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/menu/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 1,
    },
    {
        "id": 6,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/user/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 7,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/user/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 8,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/user/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 9,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/user/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 10,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/user/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 11,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/role/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 12,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/role/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 13,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/role/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 14,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/role/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 15,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/role/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 16,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/dept/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 5,
    },
    {
        "id": 17,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/dept/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 5,
    },
    {
        "id": 18,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/dept/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 5,
    },
    {
        "id": 19,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/dept/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 5,
    },
    {
        "id": 20,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/dept/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 5,
    },
    {
        "id": 21,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/menu_button/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 7,
    },
    {
        "id": 22,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/menu_button/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 7,
    },
    {
        "id": 23,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/menu_button/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 7,
    },
    {
        "id": 24,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/menu_button/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 7,
    },
    {
        "id": 25,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/button/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 8,
    },
    {
        "id": 26,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/button/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 8,
    },
    {
        "id": 27,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/button/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 8,
    },
    {
        "id": 28,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/button/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 8,
    },
    {
        "id": 29,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "保存",
        "value": "Save",
        "api": "/api/system/role/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 6,
    },
    {
        "id": 30,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/api_white_list/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 9,
    },
    {
        "id": 31,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/api_white_list/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 9,
    },
    {
        "id": 32,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/api_white_list/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 9,
    },
    {
        "id": 33,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/api_white_list/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 9,
    },
    {
        "id": 34,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/api_white_list/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 9,
    },
    {
        "id": 35,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/dictionary/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 10,
    },
    {
        "id": 36,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/dictionary/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 10,
    },
    {
        "id": 37,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/dictionary/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 10,
    },
    {
        "id": 38,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/dictionary/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 10,
    },
    {
        "id": 39,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/dictionary/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 10,
    },
    {
        "id": 40,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/area/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 11,
    },
    {
        "id": 41,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/area/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 11,
    },
    {
        "id": 42,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/area/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 11,
    },
    {
        "id": 43,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/area/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 11,
    },
    {
        "id": 44,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/area/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 11,
    },
    {
        "id": 45,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/operation_log/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 16,
    },
    {
        "id": 46,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/operation_log/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 16,
    },
    {
        "id": 47,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "导出",
        "value": "Export",
        "api": "/api/system/user/export/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 48,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "导入",
        "value": "Import",
        "api": "/api/system/user/import/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 49,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/file/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 13,
    },
    {
        "id": 50,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/file/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 13,
    },
    {
        "id": 51,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/file/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 13,
    },
    {
        "id": 52,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/file/{id}/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 13,
    },
    {
        "id": 53,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "重设密码",
        "value": "ResetPassword",
        "api": "/api/system/user/reset_password/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 54,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "重置密码",
        "value": "DefaultPassword",
        "api": "/api/system/user/reset_to_default_password/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 3,
    },
    {
        "id": 55,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/login_log/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 20,
    },
    {
        "id": 56,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/login_log/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 20,
    },
    {
        "id": 57,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "保存",
        "value": "Save",
        "api": "/api/system/role/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 4,
    },
    {
        "id": 71,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "查询",
        "value": "Search",
        "api": "/api/system/system_config/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 26,
    },
    {
        "id": 72,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "详情",
        "value": "Retrieve",
        "api": "/api/system/system_config/{id}/",
        "method": 0,
        "creator_id": 1,
        "menu_id": 26,
    },
    {
        "id": 73,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "删除",
        "value": "Delete",
        "api": "/api/system/system_config/{id}/",
        "method": 3,
        "creator_id": 1,
        "menu_id": 26,
    },
    {
        "id": 74,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "编辑",
        "value": "Update",
        "api": "/api/system/system_config/{id}/",
        "method": 2,
        "creator_id": 1,
        "menu_id": 26,
    },
    {
        "id": 75,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "新增",
        "value": "Create",
        "api": "/api/system/system_config/",
        "method": 1,
        "creator_id": 1,
        "menu_id": 26,
    },
]

role_data = [
    {
        "id": 1,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "name": "管理员",
        "key": "admin",
        "sort": 1,
        "status": 1,
        "admin": 1,
        "data_range": 3,
        "menu": [ele for ele in range(1, 27)],
        "permission": [ele.get("id") for ele in menu_button_data],
        "remark": None,
        "creator_id": 1,
    }
]

staff_data = [
    {
        "password": "pbkdf2_sha256$260000$g17x5wlSiW1FZAh1Eudchw$ZeSAqj3Xak0io8v/pmPW0BX9EX5R2zFXDwbbD68oBFk=",
        "last_login": None,
        "is_superuser": 1,
        "first_name": "",
        "last_name": "",
        "is_staff": 1,
        "is_active": 1,
        "id": 1,
        "description": None,
        "modifier": "1",
        "dept_belong_id": 1,
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "username": "superadmin",
        "email": "dvadmin@django-vue-admin.com",
        "mobile": "13333333333",
        "avatar": None,
        "name": "超级管理员",
        "gender": 1,
        "creator_id": None,
        "dept_id": 1,
    },
    {
        "password": "pbkdf2_sha256$260000$g17x5wlSiW1FZAh1Eudchw$ZeSAqj3Xak0io8v/pmPW0BX9EX5R2zFXDwbbD68oBFk=",
        "last_login": None,
        "is_superuser": 0,
        "first_name": "",
        "last_name": "",
        "is_staff": 1,
        "is_active": 1,
        "id": 2,
        "description": "",
        "modifier": "1",
        "dept_belong_id": "",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "username": "admin",
        "email": "dvadmin@django-vue-admin.com",
        "mobile": "18888888888",
        "avatar": "",
        "name": "管理员",
        "gender": 1,
        "creator_id": None,
        "dept_id": 1,
        "role": [1],
    },
]

dictionary_data = [
    {
        "id": 1,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "启用/禁用-布尔值",
            "value": "button_status_bool",
            "status": 1,
            "sort": 1,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 2,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "启用",
                    "value": "true",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 6,
                },
            },
            {
                "id": 6,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "禁用",
                    "value": "false",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 6,
                },
            },
        ],
    },
    {
        "id": 5,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "是/否-布尔值",
            "value": "button_whether_bool",
            "status": 1,
            "sort": 3,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 11,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "是",
                    "value": "true",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 6,
                },
            },
            {
                "id": 12,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "否",
                    "value": "false",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 6,
                },
            },
        ],
    },
    {
        "id": 7,
        "data": {
            "description": "",
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "启用/禁用-数字值",
            "value": "button_status_number",
            "status": 1,
            "sort": 2,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 8,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "启用",
                    "value": "1",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
            {
                "id": 9,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "禁用",
                    "value": "0",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
        ],
    },
    {
        "id": 10,
        "data": {
            "description": None,
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "是/否-数字值",
            "value": "button_whether_number",
            "status": 1,
            "sort": 4,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 13,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "是",
                    "value": "1",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
            {
                "id": 14,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "否",
                    "value": "2",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
        ],
    },
    {
        "id": 15,
        "data": {
            "description": None,
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "用户类型",
            "value": "user_type",
            "status": 1,
            "sort": 5,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 16,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "后台用户",
                    "value": "0",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
            {
                "id": 17,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "前台用户",
                    "value": "1",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
        ],
    },
    {
        "id": 18,
        "data": {
            "description": None,
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "性别",
            "value": "gender",
            "status": 1,
            "sort": 6,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
        },
        "children": [
            {
                "id": 19,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "未知",
                    "value": "0",
                    "status": 1,
                    "sort": 0,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
            {
                "id": 20,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "男",
                    "value": "1",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
            {
                "id": 21,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "女",
                    "value": "2",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                },
            },
        ],
    },
    {
        "id": 49,
        "data": {
            "description": None,
            "modifier": "1",
            "dept_belong_id": "1",
            "update_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "create_datetime": datetime.datetime(2022, 5, 18, 11, 21, 9, 288771),
            "label": "表单类型",
            "value": "config_form_type",
            "status": 1,
            "sort": 5,
            "remark": None,
            "creator_id": 1,
            "is_value": 0,
            "type": 0,
            "color": None,
        },
        "children": [
            {
                "id": 50,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "text",
                    "value": "0",
                    "status": 1,
                    "sort": 0,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 51,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "datetime",
                    "value": "1",
                    "status": 1,
                    "sort": 1,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 52,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "date",
                    "value": "2",
                    "status": 1,
                    "sort": 2,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 53,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "textarea",
                    "value": "3",
                    "status": 1,
                    "sort": 0,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 54,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "select",
                    "value": "4",
                    "status": 1,
                    "sort": 4,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 55,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "checkbox",
                    "value": "5",
                    "status": 1,
                    "sort": 5,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 56,
                "data": {
                    "description": None,
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "radio",
                    "value": "6",
                    "status": 1,
                    "sort": 6,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": None,
                },
            },
            {
                "id": 57,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "图片(单张)",
                    "value": "7",
                    "status": 1,
                    "sort": 8,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 58,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "文件附件",
                    "value": "8",
                    "status": 1,
                    "sort": 7,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 59,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "switch",
                    "value": "9",
                    "status": 1,
                    "sort": 6,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 60,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "number",
                    "value": "10",
                    "status": 1,
                    "sort": 0,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 61,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "数组",
                    "value": "11",
                    "status": 1,
                    "sort": 11,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 62,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "图片(多张)",
                    "value": "12",
                    "status": 1,
                    "sort": 9,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 63,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "关联表",
                    "value": "13",
                    "status": 1,
                    "sort": 13,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 64,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "关联表(多选)",
                    "value": "14",
                    "status": 1,
                    "sort": 14,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
            {
                "id": 65,
                "data": {
                    "description": "",
                    "modifier": "1",
                    "dept_belong_id": "1",
                    "update_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "create_datetime": datetime.datetime(
                        2022, 5, 18, 11, 21, 9, 288771
                    ),
                    "label": "time",
                    "value": "15",
                    "status": 1,
                    "sort": 3,
                    "remark": None,
                    "creator_id": 1,
                    "is_value": 1,
                    "type": 1,
                    "color": "",
                },
            },
        ],
    },
]

system_config_data = [
    {
        "id": 1,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "登录页配置",
        "key": "login",
        "value": None,
        "sort": 1,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": None,
        "placeholder": None,
        "setting": None,
        "creator_id": 1,
        "parent_id": None,
    },
    {
        "id": 2,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "网站名称",
        "key": "site_name",
        "value": "企业级后台管理系统",
        "sort": 1,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [{"message": "必填项不能为空", "required": True}],
        "placeholder": "请输入网站名称",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 3,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "登录网站logo",
        "key": "site_logo",
        "value": None,
        "sort": 2,
        "status": 1,
        "data_options": None,
        "form_item_type": 7,
        "rule": [],
        "placeholder": "请上传网站logo",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 4,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "登录页背景图",
        "key": "login_background",
        "value": None,
        "sort": 3,
        "status": 1,
        "data_options": None,
        "form_item_type": 7,
        "rule": [],
        "placeholder": "请上传登录背景页",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 5,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "版权信息",
        "key": "copyright",
        "value": "2021-2022 django-vue-admin.com 版权所有",
        "sort": 4,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [{"message": "必填项不能为空", "required": True}],
        "placeholder": "请输入版权信息",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 6,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "备案信息",
        "key": "keep_record",
        "value": "晋ICP备18005113号-3",
        "sort": 5,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [{"message": "必填项不能为空", "required": True}],
        "placeholder": "请输入备案信息",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 7,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "帮助链接",
        "key": "help_url",
        "value": "https://django-vue-admin.com",
        "sort": 6,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": "",
        "placeholder": "请输入帮助信息",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 8,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "隐私链接",
        "key": "privacy_url",
        "value": "#",
        "sort": 7,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [],
        "placeholder": "请填写隐私链接",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 9,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "条款链接",
        "key": "clause_url",
        "value": "#",
        "sort": 8,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [],
        "placeholder": "请输入条款链接",
        "setting": None,
        "creator_id": 1,
        "parent_id": 1,
    },
    {
        "id": 10,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "基础配置",
        "key": "base",
        "value": None,
        "sort": 0,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": None,
        "placeholder": None,
        "setting": None,
        "creator_id": 1,
        "parent_id": None,
    },
    {
        "id": 11,
        "description": None,
        "modifier": "1",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "开启验证码",
        "key": "captcha_state",
        "value": True,
        "sort": 1,
        "status": 1,
        "data_options": None,
        "form_item_type": 9,
        "rule": [{"message": "必填项不能为空", "required": True}],
        "placeholder": "请选择",
        "setting": None,
        "creator_id": 1,
        "parent_id": 10,
    },
    {
        "id": 12,
        "description": None,
        "modifier": "2",
        "dept_belong_id": "1",
        "update_datetime": datetime.datetime.now(),
        "create_datetime": datetime.datetime.now(),
        "title": "创建用户默认密码",
        "key": "default_password",
        "value": "admin123456",
        "sort": 2,
        "status": 1,
        "data_options": None,
        "form_item_type": 0,
        "rule": [{"message": "必填项不能为空", "required": True}],
        "placeholder": "请输入默认密码",
        "setting": None,
        "creator_id": 1,
        "parent_id": 10,
    },
]
